### PR TITLE
Updated readme

### LINKED ISSUE #52: associate link to crosswoc website to its banner
I will associate link to crosswoc website to its banner so that, when anyone clicks the crosswoc banner, it will direct them to the website of crosswoc

### LINKED ISSUE #53: I will add name and photo of maintainer in the end of readme file of your repo
like the one mentioned below 
image

### PR DESCRIPTION
**Pull request by yashlikescode**
#### Issue Number
ISSUE #52 and issue #53

#### Describe the changes you've made
Updated readme 
* Added link to crosswoc to its banner
* Added list of project maintainer and project contributors

#### Checklist

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by yashlikescode** [comment]
Please feel free to interrupt me for further modifications

**Comment by kavania2002** [comment]
Can't you add all the contributors not the top one only. All of them.

**Comment by yashlikescode** [comment]
I do have added all the contributors
no one is remaining

**Comment by yashlikescode** [comment]
image

**Comment by yashlikescode** [comment]
> Can't you add all the contributors not the top one only. All of them.

What do you mean?
Please explain more.

**Comment by kavania2002** [comment]
I mean add the photos of every contributor in the list of Project Contributors, not just only seven.

**Comment by yashlikescode** [comment]
I can find only the following contributors in your repo 
image
Please give me the lost of remaining contributors if you have,
I am not able to find anywhere

**Comment by kavania2002** [comment]
You can find from here.
https://github.com/kavania2002/MobiMart/blob/main/.github/CONTRIBUTORS.md

**Comment by yashlikescode** [comment]
yaha bhi to kewal 6 hi hain bhaiya
image

**Comment by kavania2002** [comment]
Actually, you are not one of them.
Iss pr ke baad tu bhi aa jayega 
Sweta Barnwal ka nai hai naam.

And bhaiya mat bol bro.

**Comment by yashlikescode** [comment]
okay
shweta bernwal ka naam add karna hai, ho jayega

**Comment by yashlikescode** [comment]
ab hua?

**Comment by kavania2002** [comment]
Badiya. Bohot sahi.
Thank you and happy coding.

**Pull request merged**
