### PR TITLE
Found phone which matches the background

### LINKED ISSUE #19: Find phone which matches with Background
**Describe the bug**
The iPhone mobile phones are having white background but the parent background is black, which makes the website odd.

**Expected behavior**
The background must also be black.

**Screenshots**
errorBG

**Additional context**
New features are always welcome. Thank you and enjoy coding.

### PR DESCRIPTION
**Pull request by swetakb15**
#### Issue Number
ISSUE #19 

#### Describe the changes you've made

Cleared background for few which matches with the parent background.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by swetakb15** [comment]
Made necessary changes that work with the background.

**Review by kavania2002 — COMMENTED** [review]
Hey, I can think the Redmi Logo also need's to be changed. Can you find that.

redmiError

**Comment by kavania2002** [comment]
Can you please do this also?

**Comment by swetakb15** [comment]
Actually I also thought of changing that as well but then waited for your
opinion on it.

**Comment by swetakb15** [comment]
Sure I'll do it as well.

**Comment by swetakb15** [comment]
Made few changes to the company logo.

**Pull request merged**
