### PR TITLE
Improved UI/UX for the forms 

### LINKED ISSUE #6: Improve UI/UX for the forms
Update the login and registration pages.

1. Change the font size, font family
2. Add more bootstrap in it

Do something that makes attractive.

### PR DESCRIPTION
**Pull request by Akash20x**
#### Issue Number
ISSUE #6 

#### Describe the changes you've made
Enhance design and UI of login and register page.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
This design can may be more imporved but it;s best that i can do

#### Checklist

Example how to mark a checkbox :-
- [x] My code follows the code style of this project.
-->
- [ ] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by kavania2002** [comment]
I must appreciate your work. It's just amazing. I mean it was so awesome. But just few minor errors.
You forgot to add name attribute, which is very for backend to work, and the other thing you missed is confirm password bar,
Please update this, otherwise it's perfect.

**Comment by Akash20x** [comment]
OK i will do it

**Comment by Akash20x** [comment]
Which name attribute, you are talking about and it in which file

**Comment by kavania2002** [comment]
Both the html files... anywhere we accept firstname, email, password1, password2 etc, so there name = "fname" needs to be added.
you can compare with previous code.

**Comment by Akash20x** [comment]
Done

**Comment by kavania2002** [comment]
Hey, you forgot to add in login page.

**Comment by Akash20x** [comment]
Oh so sorry, I am just forgetting little things

**Comment by kavania2002** [comment]
I am seeing that it's still not working.
Because you removed the form method and form action.
Compare it with the older one, and do it.
It will hardly take a minute.

**Comment by Akash20x** [comment]
Now, it's done

**Comment by kavania2002** [comment]
Yep, it's good. Thanks
And happy coding.

**Pull request merged**
